export const PLAY_INTERACTIVE_PIANO_NOTE = 'PLAY_INTERACTIVE_PIANO_NOTE';
export const CREATE_PRACTICE_SESSION = 'CREATE_PRACTICE SESSION';
export const CLEAR_PRACTICE_SESSION = 'CLEAR_PRACTICE SESSION';
export const CHANGE_SELECTED = 'CHANGE_SELECTED';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const INCREMENT_CORRECT_ANSWER = 'INCREMENT_CORRECT_ANSWER';